import type { Metadata } from "next";
import { DM_Sans } from "next/font/google"
import "./globals.css";

const dmSams = DM_Sans({ 
  subsets: ['latin'],
  display: "swap",
  weight:["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSams.className}>{children}</body>
    </html>
  );
}
